JAGUARETE_KAA/JAGUARETE_KAA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('miSitio/', include('miSitio.urls', namespace='miSitio')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/registro/', include("accounts.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

JAGUARETE_KAA/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



app_name='accounts'
urlpatterns = [
    path('', views.registrarse, name="registro"),
    path('logout', views.logout, name='logout'),
]

JAGUARETE_KAA/miSitio/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'miSitio'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('carrito/', views.carrito, name="carrito"),
    path('acerca_de/', views.acerca_de, name="acerca_de"),
    path('producto/', views.producto, name="ver_producto"),
    path('producto/<int:producto_id>/', views.producto, name="producto"),
    path('producto/añadir_producto/', views.añadir_producto, name="añadir_producto"),
    path('producto/<int:producto_id>/editar_producto/', views.editar_producto, name="editar_producto"),
    path('resultado_busqueda/', views.resultado_busqueda, name="resultado_busqueda"),
    path('borrar_producto/<int:producto_id>/', views.borrar_producto, name='borrar_producto'),

    path('cart/add/<int:producto_id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:producto_id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:producto_id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:producto_id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
]

JAGUARETE_KAA/miSitio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.


class Categoria(models.Model):
    descripcion = models.CharField(max_length=180)

    def __str__(self):
        return f"Categoria #{self.id}: {self.descripcion}."

    def __repr__(self):
        return "\n".join([self.descripcion])

class Producto(models.Model):
    titulo = models.CharField(max_length=64)
    imagen = models.ImageField(upload_to='')
    descripcion = models.CharField(max_length=180)
    precio = models.DecimalField(max_digits=64, decimal_places=2)
    categoria = models.ForeignKey(
        Categoria, on_delete=models.CASCADE, related_name="categoria")
    class Meta:
        verbose_name_plural = "productos"
    def __str__(self):
        return f'El Producto #{self.id}, {self.titulo}, se describe como {self.descripcion}, pertenece a la categoria {self.categoria} y tiene un precio de ${self.precio}.'


class Carrito(models.Model):
    usuario = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="usuario")
    lista_productos = models.ManyToManyField(
        Producto, blank=True, related_name="productos")
    total_carrito = models.DecimalField(max_digits=64, decimal_places=2)

    def __str__(self):
        return f"El Usuario {self.usuario}, posee un carrito con los productos: {self.lista_productos}, con un monto total de ${self.total_carrito}."

JAGUARETE_KAA/miSitio/forms.py
from django.forms import ModelForm
from django import forms
from .models import Producto

class FormProductoCRUD(forms.ModelForm):
    class Meta:
        model= Producto
        fields=('titulo','imagen','descripcion','precio','categoria')

JAGUARETE_KAA/miSitio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django import forms
from .models import Categoria, Producto, Carrito
from .forms import FormProductoCRUD
from cart.cart import Cart
# Create your views here.


def index(request):
    productos = Producto.objects.all()
    categoriax = Categoria.objects.all()
    return render(request, "misitio/index.html",{
        "productos": productos,
        "categoriax": categoriax,
    })

def carrito(request):
    lista = Carrito.lista_productos
    return render(request, "misitio/carrito.html",{
        "lista" : lista,
    })
    
# lista_productos = []

# @login_required
# def añadir_a_carrito(request,producto_id):
#     producto = get_object_or_404(Producto, pk=producto_id)
#     carrito,created = Carrito.objects.get_or_create(user=request.user, active=True)
#     Carrito.añadir_a_carrito(producto_id)
#     return render(request, 'misitio/carrito.html')
    

def acerca_de(request):
    return render(request, "misitio/acerca_de.html")

def producto(request,producto_id):
    producto = Producto.objects.get(id=producto_id)
    titulo = producto.titulo
    imagen = producto.imagen
    descripcion = producto.descripcion
    precio = producto.precio 
    categoria = producto.categoria
    return render(request, 'misitio/producto.html',{
    "producto" : producto,
    "files":Producto.objects.all(),
    "titulo": titulo,
    "precio": precio,
    "descripcion": descripcion,
    "imagen": imagen,
    "categoria":categoria,
    "producto_id":producto_id
    }
    )

def resultado_busqueda(request):
    productos = Producto.objects.all()
    query = request.GET.get("q")
    if query and query != '':
        productos = Producto.objects.filter(Q(titulo__icontains=query) | Q(categoria__descripcion__icontains=query)) 
    else:
        productos = Producto.objects.all()
    return render(request, "misitio/resultado_busqueda.html",{
        "productos": productos,
    })

@login_required
def añadir_producto(request):
    if request.method=="POST":
        form = FormProductoCRUD(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = FormProductoCRUD()
    return render(request, 'misitio/añadir_producto.html',{
            "formset":form,
            "files":Producto.objects.all(),
        })   

@login_required
def editar_producto(request,producto_id):
    un_producto = get_object_or_404(Producto,id=producto_id)
    if request.method=="POST":
        form= FormProductoCRUD(request.POST, request.FILES,instance=un_producto)
        if form.is_valid():
            form.save()
            return render(request,"misitio/editar_producto.html",{
                "Productos":Producto.objects.all(),
                "un_producto":un_producto,
            })
    else:
        form = FormProductoCRUD(instance=un_producto)
        return render(request,"misitio/editar_producto.html",{
            "un_producto":un_producto,
            "formset":form,
        })

def borrar_producto(request,producto_id):
    un_producto=get_object_or_404(Producto, id = producto_id)
    if request.method == 'POST':        
        un_producto.delete()                     

    return render(request, 'index.html', {'un_producto': un_producto})



@login_required
def cart_add(request, producto_id):
    cart = Cart(request)
    product = Producto.objects.get(id=producto_id)
    cart.add(product=product)
    return redirect("/miSitio")


@login_required(login_url="/users/login")
def item_clear(request, producto_id):
    cart = Cart(request)
    product = Producto.objects.get(id=producto_id)
    cart.remove(product)
    return redirect("/miSitio/carrito")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Producto.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required
def item_decrement(request, id):
    cart = Cart(request)
    product = Producto.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("/miSitio/carrito")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'cart/cart_detail.html')

JAGUARETE_KAA/miSitio/templates/misitio/acerca_de.html
{% extends 'misitio/layout.html' %}

{% block content %}
<div class="container mb-5 mt-4">
    <div class="row">
        <div class="col-12">
            <h1>ACERCA DE...</h1>
        </div>
    </div>
    <div class="row mt-3 mb-5">
        <div class="col-6">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum aspernatur tempore assumenda molestias vel dolores, molestiae, temporibus id esse officia voluptate. Atque velit repellendus cupiditate! Distinctio, corrupti veniam? Similique, ab?</div>
        <div class="col-6">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis incidunt minus totam quasi molestias explicabo, hic corporis adipisci, quam iusto excepturi, harum laboriosam recusandae nisi accusantium sequi. Debitis, dolore quos!</div>
    </div>

</div>
{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/añadir_producto.html
{% extends 'misitio/layout.html' %}
{% load templatetags %}

{% block content %}
{% if request.user|has_group:"Moderadores" %}
<form enctype="multipart/form-data" action="{% url 'miSitio:añadir_producto' %}" method="post">
{% csrf_token %}
<div class="container mb-5">
    <div class="row py-4 d-flex justify-content-center align-items-center">
        <div class="col-10 col-md-12 py-3">
            <h1>Titulo del producto: {{formset.titulo}}</h1>
        </div>
    </div>
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-10 col-md-6 py-4 py-md-0">
            {{formset.imagen}}
        </div>
        <div class="col-10 col-md-6 py-4 py-md-0">
            <p>Categoria:{{formset.categoria}}</p>
            <P>Descripcion:{{formset.descripcion}}</P>
            <div class="col-6">
                <span>Precio:{{formset.precio}}</span>
            </div>
            <div class="col-6 py-4 ">
                <input class="btn btn-secondary" type="submit" value="EDITAR">
            </div>
        </div>
    </div>
</div>
</form>

{% else %}

<p>No tiene permiso de ver este contenido</p>

{% endif %}

{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/carrito.html
{% extends 'misitio/layout.html' %}

{% load templatetags %}

{% load cart_tag %}

Total Length :: {{request.session.cart|length}}


{% block content %}
<div class="container mb-5 mt-4">
    <div class="row">
        <div class="col-12">
            <h1>Carrito:</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-8 col-md-12 d-flex justify-content-center align-items-left flex-column mb-4 mt-3">
            {% for key,value in request.session.cart.items %}
            <div class="col-12 d-flex flex-column h4">
                <p><span class="text-primary">Producto:</span> {{value.titulo}}</p> 
                <p><span class="text-primary">Precio:</span> {{value.precio}}, </p> 
                <p><span class="text-primary">Cantidad:</span> {{value.quantity}}.</p> 
            </div>
            <div></div>
            <div></div>
            <div class="mb-3">Total Items: {{ value.precio|multiply:value.quantity }}.</div>

            {% endfor %}
            <hr class="border border-1 border-dark">
            <span class="mt-3 h2 text-dark">Total Carrito: {{cart_total_amount}}</span>
            <hr class="border border-1 border-dark">
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-3">
            <a class="btn btn-danger" href="{% url 'miSitio:cart_clear' %}">VACIAR CARRITO</a>
            <button class="btn btn-success">FINALIZAR COMPRA</button>
        </div>
    </div>
</div>
{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/editar_producto.html
{% extends 'misitio/layout.html' %}
{% load templatetags %}

{% block content %}
{% if request.user|has_group:"Moderadores" %}
<form enctype="multipart/form-data" action="{% url 'miSitio:editar_producto' un_producto.id %}" method="post">
{% csrf_token %}
<div class="container mb-5">
    <div class="row py-4">
        <div class="col-12 py-3 my-4">
            <h1 class="my-3">Titulo del producto:
                <span class="py-3 h3">{{formset.titulo}}</span>
                </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 my-4 py-3 gx-3 h5">
            {{formset.imagen}}
        </div>
        <div class="col-12 col-md-6">
            <p class="h5">Categoria:&ensp;&ensp;{{formset.categoria}}</p>
            <P class="h5">Descripcion:&ensp;{{formset.descripcion}}</P>
            <div class="col-6 my-4">
                <span class="h5">Precio:{{formset.precio}}</span>
            </div>
            <div class="col-6 my-4">
                <input class="btn btn-secondary" type="submit" value="EDITAR" method="post" href="{% url 'miSitio:producto' un_producto.id %}"">
            </div>
        </div>
    </div>
</div>
</form>

{% else %}

<p>No tiene permiso de ver este contenido</p>

{% endif %}

{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/index.html
{% extends 'misitio/layout.html' %}
{% load templatetags %}

{% block content %}

<div class="container mb-5">
    <div class="row contenedor_cuadros justify-content-center align-items-center my-5">
        {% for producto in productos|slice:":3" %}
        <div class="cuadro_producto col-8 py-3 py-md-0 col-md-3 vw-10 vh-10 d-flex flex-column justify-content-center align-items-center">
            <h3>{{producto.titulo}}</h3>
            <img class="img-fluid w-60 rounded-circle border border-warning border-3" src="{{producto.imagen.url}}" alt="imagen">
            {% if request.user|has_group:"Moderadores" %}
            <a class="btn btn-secondary"href="{% url 'miSitio:editar_producto' producto.id %}">Ver Detalle</a>
            {%  else %}
            <a class="btn btn-secondary"href="{% url 'miSitio:producto' producto.id %}">Ver Detalle</a>
            {%  endif %}
        </div>
        {% endfor %}
    </div>



    {% if request.user|has_group:"Moderadores" %}
    <div class="row justify-content-center align-items-center d-flex  my-3">
        <div class="mas_productos col-12 d-flex justify-content-center align-items-center">MAS PRODUCTOS</div>
        <hr class="border border-1 border-dark">
        {% for producto in productos|slice:"3:10" %}
    </div>
    <div class="row justify-content-start align-items-center d-flex  my-3">
        <div class="col-12 vw-10 vh-10 d-flex flex-row"> 
        <ul>
            <li><a class="etiqueta_home_lista" href="{% url 'miSitio:editar_producto' producto.id %}">{{producto.titulo}}: {{producto.descripcion}}.</a></li>
        </ul>
    </div>
        {% endfor %}
        <hr class="border border-1 border-dark">
    </div>
    {%  else %}

    <div class="row justify-content-center align-items-center d-flex  my-3">
        <div class="mas_productos col-12 d-flex justify-content-center align-items-center">MAS PRODUCTOS</div>
        <hr class="border border-1 border-dark">
        {% for producto in productos|slice:"3:10" %} 
    </div>
    <div class="row justify-content-start align-items-center d-flex  my-3">
        <div class="col-12   vw-10 vh-10 d-flex flex-row"> 
        <ul>
            <li><a class="etiqueta_home_lista"href="{% url 'miSitio:producto' producto.id %}">{{producto.titulo}}: {{producto.descripcion}}.</a></li>
        </ul>
    </div>
        {% endfor %}
        <hr class="border border-1 border-dark">
    </div>
    {%  endif %}
</div>
{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/layout.html
{% load static %}
{% load templatetags %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'CSS/styles.css' %}">
    <title>Jaguarete KAA S.A</title>
</head>
<body>
    <header>
        <div id="header" class="container px-2 py-2">
            <div class="row d-flex align-items-center justify-content-md-between justify-content-center">
                <div class="col-md-4 col-12 d-flex ">
                    <img class="img-fluid h-20 w-70" src="{% static 'imgs/logo.png' %}" alt="logo">
                </div>
                {% if not user.is_authenticated %}
                <div class="col-4 justify-content-center align-items-center d-flex">
                    <a class="btn btn-success mx-1 mx-md-1"href="{% url 'login' %}">LOGIN</a>
                    <a class="btn btn-primary mx-1 mx-md-1"href="{% url 'accounts:registro' %}">REGISTRO</a>
                    <a class="btn btn-info mx-1 mx-md-1"href="{% url 'miSitio:carrito' %}">CARRITO</a>
                </div>
                {% endif %}
                {% if user.is_authenticated %}
                <div class="col-4 px-3 d-flex justify-content-center align-items-center">
                        <a class="btn btn-info mx-1 mx-md-1"href="{% url 'miSitio:carrito' %}">CARRITO</a>
                        <a class="btn btn-danger mx-1 mx-md-1"href="{% url 'logout' %}">LOGOUT</a>
                </div>
                {% endif %}
            </div>
        </div>
    </header>
    <nav>
        <div id="menu" class="container">
            <div class="row d-flex justify-content-md-around justify-content-center align-items-center flex-column py-2 flex-md-row">
                <div class="col-5 col-md-8 d-flex flex-column flex-md-row justify-content-md-start justify-content-center align-items-center">
                    <a class="btn btn-secondary my-2 my-md-0 me-md-2"href="{% url 'miSitio:index' %}">HOME</a>
                    <div class="btn-group my-2 my-md-0 me-md-2">
                        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">CATEGORIAS</button>
                        <ul class="dropdown-menu">
                            {% for categoria in categorias %}
                            <li class ="categoria_label"><a class="dropdown-item categoria_label" href="{% url 'miSitio:resultado_busqueda'   %}?q={{ categoria | urlencode}} ">{{categoria|cut:"'"|cut:","|cut:"("|cut:")"}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <a class="btn btn-secondary my-2 my-md-0 me-md-2 text-nowrap"href="{% url 'miSitio:acerca_de' %}">ACERCA DE</a>
                    <a class="btn btn-secondary my-2 my-md-0 me-md-2"href="mailto:yaguaretekaa@yaguarete.com" target="_blank">CONTACTO</a>
                    {% if perms.miSitio %}
                    {% if perms.miSitio.add_producto %}
                    <a class="btn btn-secondary my-2 my-md-0 me-md-2 text-nowrap"href="{% url 'miSitio:añadir_producto'%}">NUEVO PRODUCTO</a>
                    {% endif %}
                    {% else %}
                    {% endif %}
                </div>
                <div class="col-6 col-md-3 ms-md-2 my-3 my-md-0 d-flex justify-content-center align-items-center">
                    <form action="{% url 'miSitio:resultado_busqueda' %}" method="get">
                        <input name="q" type="text" placeholder="&#128270; Search...">
                    </form>
                </div>
                <div class="col-1">
                </div>
    </nav>
    {% block content %}
    {% endblock %}
    <footer>
        <div id="footer" class="container fixed-bottom d-flex align-items-center justify-content-center">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    Copyright @ 2021 JAGUARETE KAA S.A Todos los derechos Reservados / Alejandro Jonathan Messina</div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

JAGUARETE_KAA/miSitio/templates/misitio/producto.html
{% extends 'misitio/layout.html' %}
{% load templatetags %}
{% load static %}

{% block content %}
<div class="container mb-5">
    <div class="row my-4">
        <div class="col-12 my-2 justify-content-center align-items-center justify-content-md-start  d-flex">
            <h1 class="">{{titulo}}</h1>
        </div>
    </div>
    <div class="row justify-content-center align-items-center align-items-md-start mb-3">
        <div class="col-md-6 col-10">
            {% if producto.imagen %}
            <img class="img-fluid h-80 w-80 border border-dark mb-3" src="{{imagen.url}}" alt="imagen">
        {% endif %}
        </div>
        <div class="col-md-6 col-10 flex-no-wrap justify-content-center align-items-center">
            <h2 class="py-3">{{categoria}}</h2>
            <p class="h5">{{descripcion}}.</p>
            <div class="col-12 d-flex flex-row justify-content-between align-items-center py-4">
                <div class="col-3 py-3 py-md-0 ">
                    <span class="h4 py-5 py-md-3">Precio: <br> {{precio}}</span>
                </div>
                <div class="col-6">
                    {% if request.user|has_group:"Moderadores" %}
                    <a class="btn btn-secondary"href="{% url 'miSitio:editar_producto' producto_id %}">Editar</a>
                    {% endif %}
                    <a class="btn btn-success" href="{% url 'miSitio:cart_add' producto_id %}">Añadir al Carrito</a>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}

JAGUARETE_KAA/miSitio/templates/misitio/resultado_busqueda.html
{% extends 'misitio/layout.html' %}
{% load templatetags %}

{% block content %}
<div class="container mb-5 mt-5">
    <div class="row">
        <div class="col-10">
            <h1>Resultados:</h1>
            <ul>
                {% for producto in productos %}
                    <br>
                    <li><a class="etiqueta_home_lista " href="{% url 'miSitio:producto' producto.id %}">{{producto.titulo}}: {{producto.descripcion}}.</a></li>
                    <br>
                {% endfor %}
            </ul>
            {% if request.user|has_group:"Moderadores" %}
            <ul>
                {% for producto in productos %}
                    <br>
                    <li><a class="etiqueta_home_lista " href="{% url 'miSitio:editar_producto' producto.id %}">{{producto.titulo}}: {{producto.descripcion}}.</a></li>
                    <br>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}